
admin:
  user: "admin"
  password: "zu2szx12"
spring:
  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "root"
    password: "zu2szx12"
    url: "jdbc:mariadb://localhost:3306/products?createDatabaseIfNotExist=true"
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MariaDB103Dialect"
    hibernate:
      ddl-auto: update


